version: 1.2.0
config:
  style:
    # The theme defines the terminal colors used by Snipkit.
    # Available themes:default(.light|.dark),simple.
    theme: default
  # Your preferred editor to open the config file when typing 'snipkit config edit'.
  editor: "" # Defaults to a reasonable value for your operation system when empty.
  # The command which should run if you don't provide any subcommand.
  defaultRootCommand: exec # If not set, the help text will be shown.
  # Enable fuzzy searching for snippet titles.
  fuzzySearch: true
  # How secrets like access tokens are stored (see https://lemoony.github.io/snipkit/latest/configuration/overview/#secret-storage).
  secretStorage: KEYRING
  scripts:
    # The path to the shell to execute scripts with. If not set or empty, $SHELL will be used instead. Fallback is '/bin/bash'.
    shell: ""
    # Defines how parameters are handled. Allowed values: SET (sets the parameter value as shell variable) and REPLACE (replaces all occurrences of the variable with the actual value)
    parameterMode: ""
    # If set to true, any comments in your scripts will be removed upon executing or printing.
    removeComments: false
    # If set to true, the executed command is always printed on stdout before execution for confirmation (same functionality as providing flag -c/--confirm).
    execConfirm: false
    # If set to true, the executed command is always printed on stdout (same functionality as providing flag -p/--print).
    execPrint: true
  assistant:
    # Defines if you want to save the snippets created by the assistant. Possible values: NEVER | FS_LIBRARY
    saveMode: NEVER
  manager:
    pet:
      # Set to true if you want to use pet.
      enabled: true
      # List of pet snippet files.
      libraryPaths:
        - /Users/alew/Documents/code/personal_pet_snippets/snippet.toml
        - /Users/alew/Documents/code/work_pet_snippets/arsenal.toml
        - /Users/alew/Documents/code/work_pet_snippets/snippet.toml
      # If this list is not empty, only those snippets that match the listed tags will be provided to you.
      includeTags: []
    fsLibrary:
      # If set to false, the files specified via libraryPath will not be provided to you.
      enabled: true
      # Paths directories that hold snippets files (use absolute paths!). Each file must hold one snippet only.
      libraryPath:
        - /Users/alew/Documents/code/arsenal_scripts
      # Index of library path where to store snippets created by the assistant.
      assistantLibraryPathIndex: 0
      # Only files with endings which match one of the listed suffixes will be considered.
      suffixRegex:
        - .sh
      # If set to true, the files will not be parsed in advance. This means, only the filename can be used as the snippet name.
      lazyOpen: false
      # If set to true, the title comment will not be shown in the preview window.
      hideTitleInPreview: false
